<?php

namespace App\Controller\Admin;

use App\Entity\Accessories;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class AccessoriesCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Accessories::class;
    }

    public function configureFields(string $pageName): iterable
    {
        return parent::configureFields($pageName); // TODO: Change the autogenerated stub
    }
}
